name: 'GitOps for Cloudflare Email'
description: 'Apply GitOps to Cloudflare Email'
inputs:
  path:
    description: 'Configuration File Path'
    required: true
    default: 'emails.yaml'
  token:
    description: 'Cloudflare API Token'
    required: true
  apply:
    description: 'Apply'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CLOUDFLARE_API_TOKEN: ${{ inputs.token }}
  args:
    - --apply
    - ${{ inputs.path }}
